### ISSUE TITLE
Should the PDF update on keyup rather than on change?

### ISSUE THREAD

**Issue by Nightfirecat** [marumari/decklist#13]
I find it a bit odd to see the PDF display update when I tab between fields or use the arrow keys / <kbd>Home</kbd> + <kbd>Down</kbd> keys to navigate within one of the textareas. Is there any reason we need to update it whenever keys are pressed?

**Comment by marumari** [comment]
I don’t see any reason why we couldn’t do it onChange instead.  Makes sense to me!
