### ISSUE TITLE
Separate lands in decklist

### ISSUE THREAD

**Issue by JoeHughto** [marumari/decklist#17]
A vast majority of handwritten lists will have lands separate from non-lands.  It'd be nice if this could also do that while still allowing all of the different sort mechanisms.

**Comment by Nightfirecat** [comment]
Were you thinking of this as another sorting option entirely ("Lands vs. Nonlands") or just an extension to the already-existing sorting options? (something along the lines of a checkbox reading "Separate lands from Nonlands")

As-is, half of the sorting options already do this by default (CMC and Color). I take it this would apply to Alphabetical and Numerical sorting?
