### ISSUE TITLE
Add Field Validation

### ISSUE THREAD

**Issue by Nightfirecat** [marumari/decklist#5]
Need to validate the following:

- [x] DCI Number (needs to be <11 digits, only digits)
- [x] Verify main deck >= 60 cards, SB <= 15 cards (warning if not)
- [x] Verify main deck does not exceed lines available (44 unique cards)
- [x] Verify names are not too long
- [x] Verify date is future-set
- [x] Card not recognized
- [x] Duplicate cards (4x Terminus and 4x Terminus listed twice)
- [x] Any card quantity over 4, aside from basics, relentless rats, and shadowborn apostle
* ~~Banned cards for selected format~~ (different update)

**Comment by marumari** [comment]
Updating @Nightfirecat's list.

**Comment by Nightfirecat** [comment]
Turned it into a checkbox so I can see it a bit better at a glance. I think most of the new ones should be covered by what I've got already (and it won't be too hard to add the exceptions to the 4x cap rule), but we don't have a good selector for indicating format as of now.

**Comment by marumari** [comment]
Hmm, I've been working on code on my side to get it to work.  How much do you have?  I've got icons, the divs, and the css written, since I figured you had moved onto other things.

**Comment by Nightfirecat** [comment]
I've got a pretty good validation system hammered out, tooltips and a status box implemented (html/css/js), and most of the validation rules written out as of nightfirecat/decklist/4fcbc94. I think most of what was left was to write a rule to validate and/or modify (in the case of old, short ones) DCI numbers.

**Comment by marumari** [comment]
Your link didn't work for me.  :\

**Comment by Nightfirecat** [comment]
Ah, thought it would auto-link, one sec.

**Comment by Nightfirecat** [comment]
Alright, manually linked them.

**Comment by marumari** [comment]
Check out:
https://github.com/marumari/decklist/tree/sandbox

To see how I did it.  I think it's very simple in the backend CSS/HTML, and should be very easy to work with in the code -- you just have to toggle the display from none to block.

**Comment by Nightfirecat** [comment]
Yeah, I took a look - the visuals are probably nicer than what I wrote up (just used specific checkmark/"x" symbols and styled with CSS), so I can likely change what I've got. I'll actually make a github page for my fork for easier testing later.

**Comment by marumari** [comment]
Okay!  Would you like me to update my HTML to include all the possible error codes, and then commit my branch to master?

**Comment by Nightfirecat** [comment]
Nah, I'll take what I need from the sandbox branch; probably best to keep master looking as clean as we can for now.

**Comment by marumari** [comment]
Sounds good.  If we just have things like:

<div class="deckliststatus" id="dle1"><img src="images/error.png">Decklist contains &lt;60 cards.</div>
<div class="deckliststatus" id="dlw1"><img src=“images/warning.png">Decklist contains &gt;60 cards.</div>
<div class="deckliststatus" id="dle2"><img src=“images/errror.png”>Sideboard contains &gt;15 cards..</div>
<div class="deckliststatus" id="dlw2"><img src=“images/warning.png”>Sideboard contains &lt; 15 cards..</div>
<div class="deckliststatus" id="dle3"><img src=“images/error.png”>Invalid DCI number.</div>

… and so on, I think it’ll work great.  All we need to do after that point is just toggle the right class in the code.  :)

**Comment by Nightfirecat** [comment]
The system I've got set up does roughly that... I'll explain more once I get the demo of my progress so far set up. (I'll see if I can get that done during lunch today, otherwise after work)

**Comment by marumari** [comment]
Okay.  I’m just worried that we’re going to get too complicated with pushing notifications on and off the stack with callbacks and everything, when it could just be a few lines of really simple code, with all of the actual text contained in the HTML instead of the JavaScript.  :)

**Comment by Nightfirecat** [comment]
Well, the notifications themselves aren't exactly a super-simple thing. As-is, my implementation basically just creates an "error" object which stores any strikes against the rules created (60 card deck, 15 card sideboard, etc etc) and then displays them once all the checks are complete.

**Comment by Nightfirecat** [comment]
No luck during lunch... I'll have some updates this evening, I guess.

**Comment by marumari** [comment]
That’s pretty complicated, at least compared to what I had been thinking.  Not that it’s necessarily bad, just a lot trickier to keep track of then simply having a single function that iteratively goes through each error condition, setting display to none if it’s not set, and setting display to block if it is.  :)

**Comment by Nightfirecat** [comment]
The way I thought about it was that there are a couple levels of "errors" which could occur:

* Errors; obvious problems that should be resolved, including cases like your DCI number being nonnumeric, your main deck including over 44 unique cards (thus breaking the PDF design)
* Warnings; likely issues, but possible scenarios depending on the format and reason for the deck list, including cases like fields being blank, maindeck and sideboard not being exactly 60/15 cards

Thus, the overall status would depend on what the highest level of "error" is noted. It's pretty modular, as you basically only need to write a test case and an error/warning message to expand on the system.

**Comment by Nightfirecat** [comment]
Well, didn't make the time to work on this tonight, and I'll be working a long shift tomorrow night, so the earliest it looks like I'll be able to wrap this up (optimistically) is Wednesday evening.

On the other hand, I did [make a test page with the latest code I've got](http://nightfirecat.github.io/decklist/), so you can feel free to see visually how everything I wrote up works.

Planned changes:

* Generalize the unknown-cards warning message; no need to list every line that wasn't recognized; much easier to explain that there were unrecognized lines
* DCI validation. Still need to decide if we want to convert old DCIs to new DCIs on the PDF, warn the user but give them the longer DCI if they'd prefer to use that, or just warn the user without providing the longer DCI
* Remove list markup on field-hover messages if there's only one; no reason to have a bulleted item if there's not actually a list
* Merge upstream changes since the work there has started; shouldn't conflict afaik

**Comment by Nightfirecat** [comment]
UPDATES: (I updated my code [and my demo](http://nightfirecat.github.io/decklist/))

* DCI Number (needs to be <11 digits, only digits)
 * **Implemented.**
 * Still unsure about what to do with short DCI numbers. We've got the algorithm to change it if need be, but I'm not sure if that's a wise choice. You'd probably have a better idea of that as an L2--I'm a mere RA and don't have the knowledge of tournament organization to know if that's a helpful (or needed) feature. [Implementation thoughts here.](https://github.com/Nightfirecat/decklist/commit/9453c4b22a0ac966f76e0469c95ed09087f3c699)
* Verify main deck >= 60 cards, SB <= 15 cards (warning if not)
 * **Implemented.**
* Verify main deck does not exceed lines available (44 unique cards)
 * **Implemented.**
* RE: Verify names are not too long
 * **Unsure of next steps...**
 * Do we want to just clip after a certain number of characters, or do we want to get into the (possibly inevitable) task of measuring and manipulating individual PDF elements? Like one of my comments mentions, the names begin to clip out of their boxes at 14 characters at bare minimum (assuming they are all `m`s), so maybe a placeholder would be to display an error if names exceed 15 letters?
* RE: Verify date is future-set
 * **Haven't done anything for this yet**
 * Plan is to display a warning if the date is not set for day-of or future
* Card not recognized
 * **Somewhat finished.**
 * Lines which fail parsing by regex are displayed, but lines which parse correctly with bogus card names (`3 tarmowhatchamacallit`) aren't caught.
  * As my previous comment states, I need to abstract this from listing each card, as that could likely cause a lot of tooltip clutter
 * I'll integrate a check during the decklist parse to check against the card db
* Duplicate cards (4x Terminus and 4x Terminus listed twice)
 * **Maybe implemented?**
 * I see two cases you may be referencing here:
  * User inputs the same card twice along in the decklist (`1 Terminus\n ... \n1 Terminus`)
  * User inputs >4 copies of a given card across main/sideboard
 * The second case is covered--there is a check for the number of copies of a given card across the full list
 * First case could be resolved by internally merging the listings (`1 Terminus` + `2 Terminus` -> 3 Terminus), or by outputting a warning. I'll work towards the first choice here, as that seems like the better user experience
* Any card quantity over 4, aside from basics, relentless rats, and shadowborn apostle
 * **Partially implemented.**
 * Need to make exceptions for basics (and snow basics!), rats, and apostles
* Banned cards for selected format
 * **No progress.**
 * I think we need to consider what kind of user story would be taken here, and consider site scope. This may be a feature better suited for external tools to take care of.

Sorry for the big post. Just wanted to highlight all of my changes at once for individual feedback. I've got a pretty good sense of direction here, but if you've got time (and thoughts) to devote to a couple of these, the help would be appreciated.

**Comment by ChaimW** [comment]
In your demo, the DCI Number does not appear on the pdf preview

**Comment by Nightfirecat** [comment]
Ah, in my eagerness to back out of the DCI validation change in this feature, I commented out the line which set it in the first place.

> also, it loses focus when it updates the pdf

Not quite sure what you mean by that... I'm not noticing fields losing focus when the PDF updates...

**Comment by ChaimW** [comment]
If you are typing, and pause for a few seconds, it will update the pdf and lose focus on the field you were typing in. You then have to click on the field to continue. The main site used to do this.

**Comment by Nightfirecat** [comment]
What browser are you experiencing this in? I'm not seeing this on my demo page on Firefox or Chrome.

**Comment by ChaimW** [comment]
>What browser are you experiencing this in? I'm not seeing this on my demo page on Firefox or Chrome.
Chrome Version 40.0.2214.94 m

**Comment by ChaimW** [comment]
Oh, and I would move the status box above the preview.

**Comment by marumari** [comment]
A couple things that I’ve noticed:

- Having an invalid list (5 Counterbalance) generates a ?, when it should generate a red status box.  I’d recommend using my images, since they’re really nice and high quality, as well.

- The date should be allowed to be set either for today or future-set.  It shouldn’t generate a future-set error, if the date is set for today.

**Comment by Nightfirecat** [comment]
> Having an invalid list (5 Counterbalance) generates a ?, when it should generate a red status box. I’d recommend using my images, since they’re really nice and high quality, as well.

I've typically been reserving errors specifically for things which would cause the PDF to break. Should they also apply to other checks for deck validity? (I assume this means we're restricting scope specifically to constructed formats)

> The date should be allowed to be set either for today or future-set. It shouldn’t generate a future-set error, if the date is set for today.

Got it.

**Comment by marumari** [comment]
Yeah, I definitely think we should notify them about invalid decklists, which would include decks that are too small, or two many of a given card.  My next plan is to get the banned card list into cards.js.  It shouldn’t be too hard; the key will be ‘b’ and the value will be [sml], ie, Treasure Cruise would have “ml", Birthing Pod would have “m”, etc.

**Comment by Nightfirecat** [comment]
Sounds good. I'll look into expanding the comment describing validation guidelines (expanding on what the difference is between "errors" and "warnings") and change any invalid-deck type checks to assign errors instead of warnings.

**Comment by marumari** [comment]
Just checking in to see how things are going.  I hope to get the banned list stuff into cards.js soon.

**Comment by Nightfirecat** [comment]
Slowly, sadly. 50-60 hour work weeks are keeping me tired. I'll try and hammer in some more fixes this weekend. (sorry again for being so sluggish on this issue)

**Comment by marumari** [comment]
No problem.  I mean, if you want to push your changes, I can work off that branch and then push it into the main branch…. if I can figure out how to do it in git.  >_<

**Comment by Nightfirecat** [comment]
Moar updates:

* Today's date doesn't alert you that it's not future-set
* Basic lands, apostles, and rats won't cause the >4 quantity error
* (intermediate update) Separated "unparseable" and "unrecognized" as categories
 * Improved the unparseable detection (no longer tags lines composed of whitespace) and fixed the html parsing function to replace all instances in a string

Next on my plate:

* **Implement unrecognizable card detection**
* Comment the rest of my code
* Make some of my code more elegant/less hacky

Nearly done -- on the home stretch!

**Comment by marumari** [comment]
Awesome!  I’d really excited to take a look at it.  :)

**Comment by Nightfirecat** [comment]
Alright, the validation functionality should now work without issue, [see for yourself!](http://nightfirecat.github.io/decklist/)
Last on my list (see above) is to wrap up the visuals, and make my code as simple and well-documented as I can before submitting a pull request. I'll mainly be attempting to work out as many of the workarounds and hacks I wrote along the way so that everything's as straightforward as can be.
