### ISSUE TITLE
Name and DCI fields are disabled when URL posting

### ISSUE THREAD

**Issue by andreliverod** [marumari/decklist#50]
When posting a list by URL with name and dci attributes the fields are set to disabled. Can this be removed? While we like to autofill in usernames from our site we still want them to change the values easily if they need to. example link:
https://www.decklist.org/?firstname=andre&lastname=liverod&dcinumber=12345

Right now we just post blank so the users set this themselves on your site.

**Comment by april** [comment]
This is now optional behavior via setting `disableediting=true`. All fields are now editable by default.

Thanks!
