### ISSUE TITLE
Issue creating decklist with Kingpin's Pet

### ISSUE THREAD

**Issue by ChaimW** [marumari/decklist#9]
For whatever reason, I cannot get it to accept the card Kingpin's Pet, despite it being in the json file.  other cards with apostrophes work fine.

**Comment by Nightfirecat** [comment]
Are you inputting the cards in an understood format? (eg. "1 Kingpin's Pet" rather than "Kingpin's Pet")

I'm seeing it appear just fine using this: http://www.decklist.org/?deckmain=1%20Kingpin%27s%20Pet

**Comment by ChaimW** [comment]
It's not working right for color/cmc ordering.

**Comment by ChaimW** [comment]
I got it to [work](http://www.decklist.org/?deckmain=3%20Alms%20Beast%0D3%20Basilica%20Screecher%0D1%20Blood%20Baron%20of%20Vizkopa%0D1%20Custodi%20Squire%0D1%20Kingpin%27s%20Pet%0D4%20Luminate%20Primordial%0D1%20Magister%20of%20Worth%0D3%20Pontiff%20of%20Blight%0D4%20Tithe%20Drinker%0D1%20Treasury%20Thrull%0D4%20Vizkopa%20Guildmage%0D1%20Beckon%20Apparition%0D1%20Chalice%20of%20Life%0D4%20Devour%20Flesh%0D3%20False%20Cure%0D1%20Sanguine%20Bond%0D1%20Tablet%20of%20the%20Guilds%0D1%20Unburial%20Rites%0D1%20Godless%20Shrine%0D3%20Orzhov%20Guildgate%0D7%20Plains%0D11%20Swamp) now, might have been a nefarious space hiding somewhere in my [decklist](https://sites.google.com/site/cswmagic/decks/false-cure).

**Comment by Nightfirecat** [comment]
I suppose so. Glad it's working now!
